"""Emit the Kova mark as a SINGLE <path> element.

scripts/generate_icons.py extracts art with a regex that takes only the
first self-closing path element, i.e. A mark built from three path elements plus
a circle therefore loses two arms. Authoring the whole glyph as one path
keeps it compatible with the existing pipeline unchanged, and subpaths in a
single element fill with the same nonzero rule.
"""
import math, pathlib

SS = 3
SIZE = 1024
CX = CY = SIZE // 2
# Ring thickness and core size are tuned together: at a 330/250 ring the
# 80-unit arms read as thin slivers next to the core once composited on
# the squircle. A 104-unit ring and a smaller core give the three arms
# visual weight comparable to the centre, which is what makes the mark
# read as one shape rather than a dot with three stray marks.
R_OUT, R_IN, ARC_HALF, CORE_R, ARMS = 330, 226, 34, 96, 3

def polar(r, deg, cx=CX, cy=CY):
    a = math.radians(deg)
    return (cx + r * math.cos(a), cy + r * math.sin(a))

def f(p):
    return f"{p[0]:.1f} {p[1]:.1f}"

def arm(mid):
    a0, a1 = mid - ARC_HALF, mid + ARC_HALF
    # outer a0->a1 is sweep 0 (y grows downward); the return leg is sweep 1.
    return (f"M {f(polar(R_OUT, a0))} A {R_OUT} {R_OUT} 0 0 0 {f(polar(R_OUT, a1))} "
            f"L {f(polar(R_IN, a1))} A {R_IN} {R_IN} 0 0 1 {f(polar(R_IN, a0))} Z")

def core():
    # A full circle as two arcs, so the core is a subpath of the same element.
    return (f"M {f(polar(CORE_R, -90))} "
            f"A {CORE_R} {CORE_R} 0 1 0 {f(polar(CORE_R, 90))} "
            f"A {CORE_R} {CORE_R} 0 1 0 {f(polar(CORE_R, -90))} Z")

def d_attr():
    return " ".join(arm(-90 + k * (360 / ARMS)) for k in range(ARMS)) + " " + core()

def svg(fg, comment):
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}" width="{SIZE}" height="{SIZE}">
  <!--
    {comment}

    Three thick arc segments (120 deg apart) orbit a solid core. The arcs
    read as a camera iris and a stylised aperture; the gaps between them are
    what keep the silhouette legible at favicon sizes, where a filled disc
    would collapse into a blob.

    The whole glyph is ONE path element with four subpaths (three arms + the core).
    That is deliberate: scripts/generate_icons.py lifts art out with
    re.search(r"[path\\b.*?/]"), which takes only the first self-closing path
    element, so a multi-element mark silently loses everything after the
    first shape. One element keeps the icon pipeline working unchanged.

    Geometry ({SIZE} grid, centre {CX},{CY}):
      outer radius {R_OUT}, inner radius {R_IN} -] {R_OUT - R_IN} unit arms
      each arm spans {ARC_HALF * 2} deg, centred at -90 / 30 / 150
      core radius {CORE_R}

    Generated by scripts/kova/make_mark.py - edit the constants there so the
    SVG and the PNG previews cannot drift apart.
  -->
  <path fill="{fg}" d="{d_attr()}"/>
</svg>
"""

def preview(path, bg, fg, size):
    from PIL import Image, ImageDraw
    img = Image.new("RGBA", (SIZE * SS, SIZE * SS), bg)
    dr = ImageDraw.Draw(img)
    c = SIZE // 2 * SS
    for k in range(ARMS):
        mid = -90 + k * (360 / ARMS)
        a0, a1 = mid - ARC_HALF, mid + ARC_HALF
        steps = 72
        pts = [polar(R_OUT * SS, a0 + (a1 - a0) * i / steps, c, c) for i in range(steps + 1)]
        pts += [polar(R_IN * SS, a0 + (a1 - a0) * i / steps, c, c) for i in range(steps, -1, -1)]
        dr.polygon(pts, fill=fg)
    r = CORE_R * SS
    dr.ellipse([c - r, c - r, c + r, c + r], fill=fg)
    img.resize((size, size), Image.LANCZOS).save(path)

def main():
    out = pathlib.Path("assets/kova"); out.mkdir(parents=True, exist_ok=True)
    (out / "kova-mark-black.svg").write_text(
        svg("#000000", "Kova mark - black positive space, for the light squircle."), encoding="utf-8")
    (out / "kova-mark-white.svg").write_text(
        svg("#ffffff", "Kova mark - white positive space, for the dark squircle."), encoding="utf-8")
    prev = out / "preview"; prev.mkdir(parents=True, exist_ok=True)
    preview(prev / "mark-light-256.png", (255,255,255,255), (0,0,0,255), 256)
    preview(prev / "mark-dark-256.png",  (13,17,23,255),   (255,255,255,255), 256)
    preview(prev / "mark-light-32.png",  (255,255,255,255), (0,0,0,255), 32)
    print("wrote single-path mark SVGs + previews")

if __name__ == "__main__":
    main()
