#!/usr/bin/env python3
"""
Emit the Kova mark SVGs and PNG previews from one geometry definition.

Both the light (black-on-white) and dark (white-on-near-black) variants are
generated here so they cannot drift apart, and so the committed SVG provably
matches the rasterised preview.

Usage:  python scripts/kova/make_mark.py
"""
from __future__ import annotations

import math
import pathlib

SS = 3            # supersample factor for the previews
SIZE = 1024        # authoring grid
CX = CY = SIZE // 2

R_OUT = 330
R_IN = 250
ARC_HALF_DEG = 30
CORE_R = 118
ARMS = 3

LIGHT_BG = "#ffffff"
DARK_BG = "#0d1117"


def polar(r: float, deg: float, cx: float = CX, cy: float = CY) -> tuple[float, float]:
    a = math.radians(deg)
    return (cx + r * math.cos(a), cy + r * math.sin(a))


def fmt(p: tuple[float, float]) -> str:
    return f"{p[0]:.1f} {p[1]:.1f}"


def arm_path(mid_deg: float) -> str:
    """One arc segment: outer edge left-to-right, inner edge back again."""
    a0, a1 = mid_deg - ARC_HALF_DEG, mid_deg + ARC_HALF_DEG
    # sweep 0 = clockwise in SVG's coordinate system (y grows downward)
    return (
        f"M {fmt(polar(R_OUT, a0))} "
        f"A {R_OUT} {R_OUT} 0 0 1 {fmt(polar(R_OUT, a1))} "
        f"L {fmt(polar(R_IN, a1))} "
        f"A {R_IN} {R_IN} 0 0 0 {fmt(polar(R_IN, a0))} Z"
    )


def svg(fg: str, bg: str, comment: str) -> str:
    arms = "\n".join(
        f'    <path d="{arm_path(-90 + k * (360 / ARMS))}"/>' for k in range(ARMS)
    )
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {SIZE} {SIZE}" width="{SIZE}" height="{SIZE}">
  <!--
    {comment}

    Three thick arc segments (120 deg apart) orbit a solid core. The arcs
    read as a camera iris and a stylised aperture; the gaps between them are
    what keep the silhouette legible at favicon sizes, where a filled disc
    would collapse into a blob.

    Geometry ({SIZE} grid, centre {CX},{CY}):
      outer radius {R_OUT}, inner radius {R_IN} -> {R_OUT - R_IN} unit thick arcs
      each arc spans {ARC_HALF_DEG * 2} deg, centred at -90 / 30 / 150
      core disc radius {CORE_R}

    Generated by scripts/kova/make_mark.py - edit the constants there
    rather than this file, so the SVG and the PNG previews stay in step.
  -->
  <g fill="{fg}">
{arms}
    <circle cx="{CX}" cy="{CY}" r="{CORE_R}"/>
  </g>
</svg>
"""


def preview(path: pathlib.Path, bg: tuple[int, int, int, int], fg: tuple[int, int, int, int], size: int) -> None:
    from PIL import Image, ImageDraw

    img = Image.new("RGBA", (SIZE * SS, SIZE * SS), bg)
    d = ImageDraw.Draw(img)
    c = SIZE // 2 * SS
    for k in range(ARMS):
        mid = -90 + k * (360 / ARMS)
        # Walk the outer edge left-to-right, then the inner edge back again.
        # Both arcs must advance in the SAME rotational direction, otherwise
        # the ring self-intersects and the fill collapses into a bowtie.
        steps = 72
        a0, a1 = mid - ARC_HALF_DEG, mid + ARC_HALF_DEG
        pts = [polar(R_OUT * SS, a0 + (a1 - a0) * i / steps, c, c)
               for i in range(steps + 1)]
        pts += [polar(R_IN * SS, a0 + (a1 - a0) * i / steps, c, c)
                for i in range(steps, -1, -1)]
        d.polygon(pts, fill=fg)
    r = CORE_R * SS
    d.ellipse([c - r, c - r, c + r, c + r], fill=fg)
    img.resize((size, size), Image.LANCZOS).save(path)


def main() -> None:
    out = pathlib.Path("assets/kova")
    out.mkdir(parents=True, exist_ok=True)
    (out / "kova-mark-black.svg").write_text(
        svg("#000000", LIGHT_BG, "Kova mark - black positive space, for the light squircle."),
        encoding="utf-8",
    )
    (out / "kova-mark-white.svg").write_text(
        svg("#ffffff", DARK_BG, "Kova mark - white positive space, for the dark squircle."),
        encoding="utf-8",
    )

    prev = pathlib.Path("assets/kova/preview")
    prev.mkdir(parents=True, exist_ok=True)
    preview(prev / "mark-light-256.png", (255, 255, 255, 255), (0, 0, 0, 255), 256)
    preview(prev / "mark-dark-256.png", (13, 17, 23, 255), (255, 255, 255, 255), 256)
    preview(prev / "mark-light-32.png", (255, 255, 255, 255), (0, 0, 0, 255), 32)
    print(f"wrote {out}/kova-mark-{{black,white}}.svg and previews to {prev}/")


if __name__ == "__main__":
    main()
